os: osx
osx_image: xcode9.4
install:
- curl -o Unity.pkg https://download.unity3d.com/download_unity/f2cce2a5991f/MacEditorInstaller/Unity-2017.4.10f1.pkg
- sudo installer -dumplog -package Unity.pkg -target /
- curl -o WebGL.pkg http://netstorage.unity3d.com/unity/f2cce2a5991f/MacEditorTargetInstaller/UnitySetup-WebGL-Support-for-Editor-2017.4.10f1.pkg
- sudo installer -dumplog -package WebGL.pkg -target /
script:
- ./build.bash
deploy:
  provider: pages
  local-dir: ./Build/webgl
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
